// Puzzle definition parsing and group-element helpers.
//
// A puzzle has `n` piece locations (<= 256). Every piece starts at the location
// with its own index. A move is stored as an "action":
//     new[p] = old[src[p]] + tw[p]        (orientation arithmetic mod ori[p])
// which is the same convention as the original Batch Solver, so that the cycle
// notation (A B C) means "the piece at A moves to B, the piece at B moves to C...".
// The twist written next to a piece in a cycle is added to that piece as it
// leaves its location.

export class BatchError extends Error {}

export const MAX_PIECES = 256;
export const MAX_MOVES = 1024;
export const MAX_ORIENTATIONS = 8;

const mod = (a, n) => ((a % n) + n) % n;

// ---------------------------------------------------------------- actions ---

export function identityAction(n) {
    const src = new Uint8Array(n);
    for (let i = 0; i < n; i++) src[i] = i;
    return { src, tw: new Uint8Array(n) };
}

/** Apply `a`, then `b`. `ori[p]` is the orientation count of location p. */
export function compose(a, b, ori) {
    const n = a.src.length;
    const src = new Uint8Array(n), tw = new Uint8Array(n);
    for (let p = 0; p < n; p++) {
        const q = b.src[p];
        src[p] = a.src[q];
        tw[p] = (a.tw[q] + b.tw[p]) % ori[p];
    }
    return { src, tw };
}

export function invert(a, ori) {
    const n = a.src.length;
    const src = new Uint8Array(n), tw = new Uint8Array(n);
    for (let p = 0; p < n; p++) {
        src[a.src[p]] = p;
        tw[a.src[p]] = mod(-a.tw[p], ori[p]);
    }
    return { src, tw };
}

export function isIdentity(a) {
    for (let p = 0; p < a.src.length; p++) if (a.src[p] !== p || a.tw[p] !== 0) return false;
    return true;
}

export function actionKey(a) {
    return String.fromCharCode(...a.src) + "|" + String.fromCharCode(...a.tw);
}

export function actionsEqual(a, b) {
    for (let p = 0; p < a.src.length; p++) if (a.src[p] !== b.src[p] || a.tw[p] !== b.tw[p]) return false;
    return true;
}

/** Multiplicative order of an action (number of repeats to reach the identity). */
export function actionOrder(a, ori, cap = 100000) {
    let cur = a;
    for (let k = 1; k <= cap; k++) {
        if (isIdentity(cur)) return k;
        cur = compose(cur, a, ori);
    }
    throw new BatchError("A move has an order larger than " + cap + ", which is not supported.");
}

/**
 * Enumerates the group generated by `gens` (actions), breadth first.
 * Returns [{action, seq}] where seq is a shortest list of generator indices.
 */
export function enumerateGroup(gens, ori, cap = 2000) {
    const n = ori.length;
    const id = identityAction(n);
    const seen = new Map([[actionKey(id), 0]]);
    const out = [{ action: id, seq: [] }];
    for (let head = 0; head < out.length; head++) {
        for (let g = 0; g < gens.length; g++) {
            const next = compose(out[head].action, gens[g], ori);
            const key = actionKey(next);
            if (!seen.has(key)) {
                seen.set(key, out.length);
                out.push({ action: next, seq: out[head].seq.concat(g) });
                if (out.length > cap) throw new BatchError("An adjust group has more than " + cap + " elements, which is too many.");
            }
        }
    }
    return out;
}

// ----------------------------------------------------------------- parsing ---

const NAME_RE = /^[A-Za-z0-9]+$/;

function validateMoveName(name) {
    if (!NAME_RE.test(name)) {
        throw new BatchError("'" + name + "' is not a valid move name, because move names must only contain alphanumeric characters.");
    }
    if (/[0-9]$/.test(name)) {
        throw new BatchError("'" + name + "' is not a valid move name, because move names cannot end in a number.");
    }
}

/** "R2'" -> {name:"R", power:2, inverse:true}. Returns null if the token is malformed. */
export function parseMoveToken(token) {
    let inverse = false;
    let rest = token;
    if (rest.endsWith("'")) { inverse = true; rest = rest.slice(0, -1); }
    const m = /^(.*[A-Za-z])(\d*)$/.exec(rest);
    if (!m) return null;
    return { name: m[1], power: m[2] === "" ? 1 : parseInt(m[2], 10), inverse };
}

/**
 * @typedef {{name:string, src:Uint8Array, tw:Uint8Array, base:string, index:number}} Move
 * @typedef {{n:number, pieceNames:string[], pieceIndex:Map<string,number>, ori:Uint8Array,
 *            moves:Move[], moveIndex:Map<string,number>, inverse:Int32Array,
 *            generators:Map<string,{action:object, multi:boolean}>}} Puzzle
 */

/** @param {string} text @return {Puzzle} */
export function parsePuzzle(text) {
    const pieceNames = [], oriList = [];
    const pieceIndex = new Map();
    const defs = [];
    const defByName = new Map();

    function pieceId(name) {
        let id = pieceIndex.get(name);
        if (id === undefined) {
            id = pieceNames.length;
            if (id >= MAX_PIECES) throw new BatchError("Puzzles with more than " + MAX_PIECES + " pieces are not supported.");
            pieceIndex.set(name, id);
            pieceNames.push(name);
            const caps = (name.match(/[A-Z]/g) || []).length;
            const o = Math.max(1, caps);
            if (o > MAX_ORIENTATIONS) throw new BatchError("Piece '" + name + "' has " + o + " orientations; at most " + MAX_ORIENTATIONS + " are supported.");
            oriList.push(o);
        }
        return id;
    }

    const lines = text.split(/\r?\n/);
    for (let ln = 0; ln < lines.length; ln++) {
        const line = lines[ln].split("//")[0].trim();
        if (line === "") continue;
        const head = /^([^\s:<>\-]+)\s*(<->|->|:)([\s\S]*)$/.exec(line);
        if (!head) throw new BatchError("Puzzle line " + (ln + 1) + " has no ':', '->' or '<->' (expected 'MoveName: ...').");
        const name = head[1];
        const kind = head[2] === ":" ? "all" : head[2] === "->" ? "one" : "pair";
        const body = head[3];
        validateMoveName(name);
        if (defByName.has(name)) throw new BatchError("Move '" + name + "' is defined more than once.");
        const def = { name, kind, line: ln + 1 };
        if (body.includes("(") || body.includes(")")) {
            def.cycles = [];
            const re = /\(([^()]*)\)/g;
            let m, last = 0, leftover = "";
            while ((m = re.exec(body)) !== null) {
                leftover += body.slice(last, m.index);
                last = re.lastIndex;
                const cycle = [];
                for (const tok of m[1].split(/\s+/).filter(x => x !== "")) {
                    const pm = /^([^+\-]+)([+-]\d+)?$/.exec(tok);
                    if (!pm) throw new BatchError("Cannot read '" + tok + "' in move '" + name + "'.");
                    cycle.push([pieceId(pm[1]), pm[2] === undefined ? 0 : parseInt(pm[2], 10)]);
                }
                def.cycles.push(cycle);
            }
            leftover += body.slice(last);
            if (leftover.trim() !== "") throw new BatchError("Unexpected text '" + leftover.trim() + "' in the definition of move '" + name + "' (check parentheses).");
        } else {
            def.tokens = body.trim().split(/\s+/).filter(x => x !== "");
            if (def.tokens.length === 0) throw new BatchError("Move '" + name + "' has an empty definition.");
        }
        defs.push(def);
        defByName.set(name, def);
    }
    if (defs.length === 0) throw new BatchError("The Puzzle field defines no moves.");

    const n = pieceNames.length;
    if (n < 1) throw new BatchError("The Puzzle field defines no pieces.");
    const ori = Uint8Array.from(oriList);

    // ---- resolve actions (cycle definitions first, then composites on demand)
    const actionOf = new Map(); // base name -> action
    const resolving = new Set();

    function cycleAction(def) {
        const act = identityAction(n);
        const used = new Set();
        for (const cycle of def.cycles) {
            const o0 = ori[cycle[0][0]];
            for (const [pc] of cycle) {
                if (ori[pc] !== o0) throw new BatchError("In move '" + def.name + "', pieces '" + pieceNames[cycle[0][0]] + "' and '" + pieceNames[pc] + "' are in the same cycle but have different numbers of orientations.");
            }
            const edge = (from, to, twist) => {
                act.src[to] = from;
                act.tw[to] = mod(twist, ori[from]);
            };
            for (let i = 0; i < cycle.length - 1; i++) edge(cycle[i][0], cycle[i + 1][0], cycle[i][1]);
            const first = cycle[0][0], lastEntry = cycle[cycle.length - 1];
            const openChain = cycle.length > 1 && first === lastEntry[0];
            if (!openChain) edge(lastEntry[0], first, lastEntry[1]);
            for (let i = 0; i < cycle.length; i++) {
                if (i === cycle.length - 1 && openChain) continue;
                if (used.has(cycle[i][0])) throw new BatchError("In move '" + def.name + "', piece '" + pieceNames[cycle[i][0]] + "' appears more than once.");
                used.add(cycle[i][0]);
            }
        }
        return act;
    }

    function resolve(name) {
        if (actionOf.has(name)) return actionOf.get(name);
        const def = defByName.get(name);
        if (!def) return null;
        if (resolving.has(name)) throw new BatchError("Move '" + name + "' is defined in terms of itself.");
        resolving.add(name);
        let act;
        if (def.cycles) act = cycleAction(def);
        else {
            act = identityAction(n);
            for (const tok of def.tokens) {
                const pt = parseMoveToken(tok);
                if (!pt) throw new BatchError("Cannot read '" + tok + "' in the definition of move '" + name + "'.");
                const base = resolve(pt.name);
                if (!base) throw new BatchError("'" + tok + "' in the definition of move '" + name + "' refers to '" + pt.name + "', which is not a defined move.");
                let step = pt.inverse ? invert(base, ori) : base;
                for (let r = 0; r < pt.power; r++) act = compose(act, step, ori);
            }
        }
        resolving.delete(name);
        actionOf.set(name, act);
        return act;
    }
    for (const def of defs) resolve(def.name);

    // ---- expand into concrete moves
    const moves = [];
    const moveIndex = new Map();
    const keyToMove = new Map();
    const generators = new Map();

    function addMove(name, act, base) {
        if (moveIndex.has(name)) throw new BatchError("Move name '" + name + "' is produced more than once.");
        const key = actionKey(act);
        if (keyToMove.has(key)) { // identical action: just an alias of an earlier move
            moveIndex.set(name, keyToMove.get(key));
            return;
        }
        const index = moves.length;
        if (index >= MAX_MOVES) throw new BatchError("Too many moves (more than " + MAX_MOVES + ").");
        moves.push({ name, src: act.src, tw: act.tw, base, index });
        keyToMove.set(key, index);
        moveIndex.set(name, index);
    }

    for (const def of defs) {
        const act = actionOf.get(def.name);
        if (isIdentity(act)) throw new BatchError("Move '" + def.name + "' does nothing (it is the identity).");
        const order = actionOrder(act, ori);
        generators.set(def.name, { action: act, kind: def.kind, order });
        if (def.kind === "all") {
            // U: every multiple (U, U2, U'), as separate moves
            let cur = act;
            for (let j = 1; j < order; j++) {
                let nm;
                if (j <= order / 2) nm = def.name + (j !== 1 ? j : "");
                else nm = def.name + ((order - j) !== 1 ? (order - j) : "") + "'";
                addMove(nm, cur, def.name);
                cur = compose(cur, act, ori);
            }
        } else {
            // U <-> defines U and U', U -> defines only U
            addMove(def.name, act, def.name);
            if (order === 2) moveIndex.set(def.name + "'", moveIndex.get(def.name));
            else if (def.kind === "pair") addMove(def.name + "'", invert(act, ori), def.name);
        }
    }

    // ---- inverse table (-1: the inverse of a one-way `->` move is not itself a move)
    const inverse = new Int32Array(moves.length).fill(-1);
    for (const mv of moves) {
        const idx = keyToMove.get(actionKey(invert(mv, ori)));
        if (idx !== undefined) inverse[mv.index] = idx;
    }

    return { n, pieceNames, pieceIndex, ori, moves, moveIndex, inverse, generators, defs, keyToMove };
}

/**
 * Expands one scramble/composite token ("R", "R'", "U2", "Sledge'") into move indices.
 * Exact move names win; otherwise name+power+prime is interpreted as repetition.
 */
export function expandToken(puzzle, token) {
    const exact = puzzle.moveIndex.get(token);
    if (exact !== undefined) return [exact];
    const pt = parseMoveToken(token);
    const gen = pt && puzzle.generators.get(pt.name);
    if (!gen) return null;
    const fwd = puzzle.moveIndex.get(pt.name), back = puzzle.moveIndex.get(pt.name + "'");
    const repeat = (m, times) => new Array(times).fill(m);
    if (!pt.inverse && fwd !== undefined) return repeat(fwd, pt.power);
    if (pt.inverse && back !== undefined) return repeat(back, pt.power);
    if (fwd !== undefined) {
        // one-way move (`U ->`): U' is the same as going the long way round
        const times = (gen.order - (pt.power % gen.order)) % gen.order;
        return repeat(fwd, times);
    }
    return null;
}

/** Splits a move-list field such as "R U, F" / "<R U>" on spaces and commas. */
export function splitMoveList(s) {
    return s.replace(/[(){}<>\[\]]/g, "").replaceAll(",", " ").split(/\s+/).filter(x => x !== "");
}

/** Resolves move names in a field to move indices, throwing a helpful error. */
export function resolveMoveNames(puzzle, names, where) {
    return names.map(nm => {
        const idx = puzzle.moveIndex.get(nm);
        if (idx === undefined) throw new BatchError('"' + nm + '" is not a valid move in ' + where + ".");
        return idx;
    });
}

/**
 * Turns the entries of a Subgroup / Pre-Adjust / Post-Adjust field into a sorted list of move indices.
 * An entry naming a defined move family ("U" or "U'") selects every move that family defines
 * (U, U2, U' for "U:"; U, U' for "U <->"; just U for "U ->"). Any other defined move ("U2", "Sledge'")
 * selects that move and, if it exists, its inverse.
 */
export function selectMoves(puzzle, entries, where) {
    const chosen = new Set();
    for (const entry of entries) {
        const idx = puzzle.moveIndex.get(entry);
        if (idx === undefined) throw new BatchError('"' + entry + '" is not a valid move in ' + where + ".");
        const pt = parseMoveToken(entry);
        const gen = pt && pt.power === 1 ? puzzle.generators.get(pt.name) : undefined;
        if (gen && (entry === pt.name || entry === pt.name + "'")) {
            let cur = gen.action;
            for (let k = 1; k < gen.order; k++) {
                const m = puzzle.keyToMove.get(actionKey(cur));
                if (m !== undefined && puzzle.moves[m].base === pt.name) chosen.add(m);
                cur = compose(cur, gen.action, puzzle.ori);
            }
        } else {
            chosen.add(idx);
            if (puzzle.inverse[idx] >= 0) chosen.add(puzzle.inverse[idx]);
        }
    }
    return [...chosen].sort((a, b) => a - b);
}
