// AUTO-GENERATED by generate_rotation_tables.py. Do not edit by hand.
#pragma once

// The 6 ways a whole-cube rotation can permute the {UD,LR,FB} axis-pairs
// (identity, 3 transpositions, 2 three-cycles -- the S3 quotient of the
// 24-element whole-cube rotation group). Convention matches CENTER_PERM/
// WING_PERM: PERM[s] = destination slot of the piece at slot s.
//
// ROTATE_CENTER[c]/ROTATE_WING[c] is the FORWARD rotation: applying it to
// the SOLVED state produces class c's (ud,lr,fb) target triple (see
// ROT_TARGETS in chain12.cpp). ROTATE_CENTER_INV[c]/ROTATE_WING_INV[c] is
// its inverse: apply THIS to a state already satisfying class c's target
// triple to bring it to canonical (ud=lr=fb=UD_SOLVED_IDX), before
// starting phase 2 -- this is the rotation chain12.cpp actually performs
// and must record (as free, uncounted notation) in its output solution.
// ROTATE_CLASS_INV_NOTATION[c] is that inverse rotation's standard WCA
// whole-cube-rotation name (x/x2/x'/y/y2/y'/z/z2/z', or "" for identity).
// Class order matches ROTATE_CLASS_NAMES. Classes 6..8 are the whole-cube half turns x2, y2, z2 (involutions:
// forward == inverse); they are not S1 classes, only the S4 canonicalization rotations (see CLAUDE.md).
static const int NUM_ROTATE_CLASSES = 9;

static const char* ROTATE_CLASS_NAMES[9] = {
    "identity", "swap_UD_FB", "swap_UD_LR", "swap_LR_FB", "cycle_UD_LR_FB", "cycle_UD_FB_LR", "klein_x2", "klein_y2", "klein_z2"
};

static const char* ROTATE_CLASS_FWD_NOTATION[9] = {
    "", "x", "z", "y", "x y", "x z", "x2", "y2", "z2"
};

static const char* ROTATE_CLASS_INV_NOTATION[9] = {
    "", "x'", "z'", "y'", "x' z'", "x' y", "x2", "y2", "z2"
};

static const int ROTATE_CENTER[9][24] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // identity
    {1, 3, 0, 2, 7, 9, 5, 11, 4, 10, 6, 8, 15, 17, 13, 19, 12, 18, 14, 16, 21, 23, 20, 22}, // swap_UD_FB
    {10, 11, 18, 19, 2, 3, 8, 9, 16, 17, 22, 23, 0, 1, 6, 7, 14, 15, 20, 21, 4, 5, 12, 13}, // swap_UD_LR
    {14, 6, 16, 8, 12, 4, 20, 0, 22, 2, 18, 10, 13, 5, 21, 1, 23, 3, 19, 11, 15, 7, 17, 9}, // swap_LR_FB
    {6, 8, 14, 16, 0, 2, 4, 10, 12, 18, 20, 22, 1, 3, 5, 11, 13, 19, 21, 23, 7, 9, 15, 17}, // cycle_UD_LR_FB
    {11, 19, 10, 18, 9, 17, 3, 23, 2, 22, 8, 16, 7, 15, 1, 21, 0, 20, 6, 14, 5, 13, 4, 12}, // cycle_UD_FB_LR
    {3, 2, 1, 0, 11, 10, 9, 8, 7, 6, 5, 4, 19, 18, 17, 16, 15, 14, 13, 12, 23, 22, 21, 20}, // klein_x2
    {21, 20, 23, 22, 13, 12, 15, 14, 17, 16, 19, 18, 5, 4, 7, 6, 9, 8, 11, 10, 1, 0, 3, 2}, // klein_y2
    {22, 23, 20, 21, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1}, // klein_z2
};

static const int ROTATE_WING[9][24] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // identity
    {3, 5, 1, 7, 0, 6, 2, 4, 9, 11, 8, 10, 13, 15, 12, 14, 19, 21, 17, 23, 16, 22, 18, 20}, // swap_UD_FB
    {6, 7, 10, 11, 14, 15, 22, 23, 4, 5, 20, 21, 2, 3, 18, 19, 0, 1, 8, 9, 12, 13, 16, 17}, // swap_UD_LR
    {12, 8, 18, 2, 20, 4, 14, 10, 16, 0, 22, 6, 17, 1, 23, 7, 13, 9, 19, 3, 21, 5, 15, 11}, // swap_LR_FB
    {2, 4, 8, 10, 12, 14, 18, 20, 0, 6, 16, 22, 1, 7, 17, 23, 3, 5, 9, 11, 13, 15, 19, 21}, // cycle_UD_LR_FB
    {11, 15, 7, 23, 6, 22, 10, 14, 5, 21, 4, 20, 3, 19, 2, 18, 9, 13, 1, 17, 0, 16, 8, 12}, // cycle_UD_FB_LR
    {7, 6, 5, 4, 3, 2, 1, 0, 11, 10, 9, 8, 15, 14, 13, 12, 23, 22, 21, 20, 19, 18, 17, 16}, // klein_x2
    {17, 16, 19, 18, 21, 20, 23, 22, 13, 12, 15, 14, 9, 8, 11, 10, 1, 0, 3, 2, 5, 4, 7, 6}, // klein_y2
    {22, 23, 20, 21, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1}, // klein_z2
};

// Corner STICKER relabeling (24 = 8 positions x 3 axes, local index
// pos_idx*3+axis -- see tables5.h/generate_tables5.py). Same convention
// and same pure-relabeling semantics as ROTATE_CENTER/ROTATE_WING --
// verified against direct 96-sticker composition, 200 random states x 6
// classes, 0 mismatches (see chat). Deriving corner ORIENTATION (the 3^7
// phase-5 coordinate) from a corner_sticker_slot array is a separate,
// stateless computation -- see chain1234prime.cpp / tables5.h -- so no
// twist-relabeling table is needed here at all.
static const int ROTATE_CORNER[9][24] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // identity
    {3, 5, 4, 9, 11, 10, 0, 2, 1, 6, 8, 7, 15, 17, 16, 21, 23, 22, 12, 14, 13, 18, 20, 19}, // swap_UD_FB
    {7, 6, 8, 10, 9, 11, 19, 18, 20, 22, 21, 23, 1, 0, 2, 4, 3, 5, 13, 12, 14, 16, 15, 17}, // swap_UD_LR
    {14, 13, 12, 2, 1, 0, 20, 19, 18, 8, 7, 6, 17, 16, 15, 5, 4, 3, 23, 22, 21, 11, 10, 9}, // swap_LR_FB
    {2, 0, 1, 8, 6, 7, 14, 12, 13, 20, 18, 19, 5, 3, 4, 11, 9, 10, 17, 15, 16, 23, 21, 22}, // cycle_UD_LR_FB
    {10, 11, 9, 22, 23, 21, 7, 8, 6, 19, 20, 18, 4, 5, 3, 16, 17, 15, 1, 2, 0, 13, 14, 12}, // cycle_UD_FB_LR
    {9, 10, 11, 6, 7, 8, 3, 4, 5, 0, 1, 2, 21, 22, 23, 18, 19, 20, 15, 16, 17, 12, 13, 14}, // klein_x2
    {15, 16, 17, 12, 13, 14, 21, 22, 23, 18, 19, 20, 3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8}, // klein_y2
    {18, 19, 20, 21, 22, 23, 12, 13, 14, 15, 16, 17, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5}, // klein_z2
};

static const int ROTATE_CENTER_INV[9][24] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // identity
    {2, 0, 3, 1, 8, 6, 10, 4, 11, 5, 9, 7, 16, 14, 18, 12, 19, 13, 17, 15, 22, 20, 23, 21}, // swap_UD_FB
    {12, 13, 4, 5, 20, 21, 14, 15, 6, 7, 0, 1, 22, 23, 16, 17, 8, 9, 2, 3, 18, 19, 10, 11}, // swap_UD_LR
    {7, 15, 9, 17, 5, 13, 1, 21, 3, 23, 11, 19, 4, 12, 0, 20, 2, 22, 10, 18, 6, 14, 8, 16}, // swap_LR_FB
    {4, 12, 5, 13, 6, 14, 0, 20, 1, 21, 7, 15, 8, 16, 2, 22, 3, 23, 9, 17, 10, 18, 11, 19}, // cycle_UD_LR_FB
    {16, 14, 8, 6, 22, 20, 18, 12, 10, 4, 2, 0, 23, 21, 19, 13, 11, 5, 3, 1, 17, 15, 9, 7}, // cycle_UD_FB_LR
    {3, 2, 1, 0, 11, 10, 9, 8, 7, 6, 5, 4, 19, 18, 17, 16, 15, 14, 13, 12, 23, 22, 21, 20}, // klein_x2
    {21, 20, 23, 22, 13, 12, 15, 14, 17, 16, 19, 18, 5, 4, 7, 6, 9, 8, 11, 10, 1, 0, 3, 2}, // klein_y2
    {22, 23, 20, 21, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1}, // klein_z2
};

static const int ROTATE_WING_INV[9][24] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // identity
    {4, 2, 6, 0, 7, 1, 5, 3, 10, 8, 11, 9, 14, 12, 15, 13, 20, 18, 22, 16, 23, 17, 21, 19}, // swap_UD_FB
    {16, 17, 12, 13, 8, 9, 0, 1, 18, 19, 2, 3, 20, 21, 4, 5, 22, 23, 14, 15, 10, 11, 6, 7}, // swap_UD_LR
    {9, 13, 3, 19, 5, 21, 11, 15, 1, 17, 7, 23, 0, 16, 6, 22, 8, 12, 2, 18, 4, 20, 10, 14}, // swap_LR_FB
    {8, 12, 0, 16, 1, 17, 9, 13, 2, 18, 3, 19, 4, 20, 5, 21, 10, 14, 6, 22, 7, 23, 11, 15}, // cycle_UD_LR_FB
    {20, 18, 14, 12, 10, 8, 4, 2, 22, 16, 6, 0, 23, 17, 7, 1, 21, 19, 15, 13, 11, 9, 5, 3}, // cycle_UD_FB_LR
    {7, 6, 5, 4, 3, 2, 1, 0, 11, 10, 9, 8, 15, 14, 13, 12, 23, 22, 21, 20, 19, 18, 17, 16}, // klein_x2
    {17, 16, 19, 18, 21, 20, 23, 22, 13, 12, 15, 14, 9, 8, 11, 10, 1, 0, 3, 2, 5, 4, 7, 6}, // klein_y2
    {22, 23, 20, 21, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1}, // klein_z2
};

static const int ROTATE_CORNER_INV[9][24] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // identity
    {6, 8, 7, 0, 2, 1, 9, 11, 10, 3, 5, 4, 18, 20, 19, 12, 14, 13, 21, 23, 22, 15, 17, 16}, // swap_UD_FB
    {13, 12, 14, 16, 15, 17, 1, 0, 2, 4, 3, 5, 19, 18, 20, 22, 21, 23, 7, 6, 8, 10, 9, 11}, // swap_UD_LR
    {5, 4, 3, 17, 16, 15, 11, 10, 9, 23, 22, 21, 2, 1, 0, 14, 13, 12, 8, 7, 6, 20, 19, 18}, // swap_LR_FB
    {1, 2, 0, 13, 14, 12, 4, 5, 3, 16, 17, 15, 7, 8, 6, 19, 20, 18, 10, 11, 9, 22, 23, 21}, // cycle_UD_LR_FB
    {20, 18, 19, 14, 12, 13, 8, 6, 7, 2, 0, 1, 23, 21, 22, 17, 15, 16, 11, 9, 10, 5, 3, 4}, // cycle_UD_FB_LR
    {9, 10, 11, 6, 7, 8, 3, 4, 5, 0, 1, 2, 21, 22, 23, 18, 19, 20, 15, 16, 17, 12, 13, 14}, // klein_x2
    {15, 16, 17, 12, 13, 14, 21, 22, 23, 18, 19, 20, 3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8}, // klein_y2
    {18, 19, 20, 21, 22, 23, 12, 13, 14, 15, 16, 17, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5}, // klein_z2
};
