// The S3'->S4 pair tables T1 = layer x ud and T2 = (eq, pll, lr, fb) x ud, reduced by symmetry.
//
// Both are the distance to the nearest S4 goal (the literal S4 and its images under x2, y2, z2, see state.h) over the 13
// S3'-set moves. Symmetries of the coordinates leave them invariant:
//   * the 16 cube symmetries of symtab.h (the sign flips of the axes, with or without swapping x and z), acting by
//     conjugation. They map the move set onto itself only up to whole-cube half turns, which is exactly the freedom the
//     "S4 up to a half turn" goals absorb: that is why the tables are invariant under them;
//   * the left multiplication by x2, y2, z2 (a relabeling of the slots), which permutes the four goals. It is defined on
//     the layer and ud coordinates only: on lr and fb it can leave the 24 classes that the moves reach, so T2 does without.
// So T1 uses a group generated by all 19 maps and T2 the one generated by the 16 conjugations.
// A symmetry acts separately on each coordinate (ud: 2520, layer: 20160, rest = eq,pll,lr,fb: 4608); the maps of one
// symmetry are found by realizing a coordinate value as a real set of pieces, applying the symmetry and reading the coordinates
// back (nothing is derived by hand), and the group is the closure of these maps.
//
// Reduction: the ud coordinate is split into its orbits ("classes"); the reduced table of class c holds the full table's row of
// the orbit's representative ud, with b (layer or rest) as it is. A lookup (b, ud) takes the class c of ud and the element h of
// the group that maps ud to the representative, and reads row c at h(b). That is exact because every group element leaves the
// full table invariant (checked on every entry with `--check-s4-sym`). The elements are NOT graph automorphisms (a wide move is
// sent to "that move followed by a half turn", which is no generator; only the distance to the goal SET is invariant), so the
// reduced table cannot be built by a BFS inside the reduced space: it is cut out of the full table, which a BFS from the four
// goals makes in a few seconds. The reduced tables (~3.5 MB) are what is stored in the cache files: the 62 MB of full tables
// never leave memory, and only on the first run (or when the coordinates, goals or symmetries change) are they built.
#pragma once
#include <unordered_set>
#include <fstream>
#include "symtab.h"

namespace s4sym {

static const int N_LAYER = 20160, N_REST = 4608, N_UD = 2520;
// Entries are stored in 4 bits: distances above DIST_CAP read as DIST_CAP. That is still an admissible lower bound (and still
// 1-Lipschitz); only the 16 / 17 entries of the full tables (a handful of the far states) lose their last bit of tightness.
static const int DIST_CAP = 15;

// One table's symmetry group, classes of ud and the reduced table. The group elements are their images of the two coordinates
// the table is over: ud, and b (layer for T1, rest for T2).
struct Reduced {
    int nb = 0;
    std::vector<std::vector<uint16_t>> ud, b;   // [element][value]; element 0 = identity
    std::vector<uint16_t> bmap;                 // [element * nb + value], flat copy of b
    std::vector<uint32_t> ud_info;              // [ud] -> (class << 8) | element mapping ud to its class representative
    std::vector<uint16_t> class_rep;            // [class] -> representative ud
    int nclass = 0;
    std::vector<uint8_t> table;                 // nibble-packed, entry [class * nb + b'] in nibble i&1 of byte i>>1, values capped at DIST_CAP
    size_t elems() const { return ud.size(); }
    size_t bytes() const { return table.size() + bmap.size() * 2 + ud_info.size() * 4; }
    inline int get(size_t i) const { return (table[i >> 1] >> ((i & 1) << 2)) & 15; }
    // the (capped) distance of (b, ud)
    inline int dist(int bv, int u) const {
        const uint32_t info = ud_info[u];
        return get((size_t)(info >> 8) * nb + bmap[(size_t)(info & 255) * nb + bv]);
    }
};
static Reduced R1, R2;                  // T1 (b = layer), T2 (b = rest)
static double g_build_ms = 0;

// ---------------------------------------------------------------- coordinates <-> pieces
// raw (domain) value of each dense coordinate id, and the pieces realizing a coordinate value (all other coordinates solved)
static std::vector<int> RAW_LAYER, RAW_EQ, RAW_UD, RAW_LR, RAW_FB;

// A coordinate value stands for a whole class of piece arrangements, and a symmetry that swaps axes sends an arrangement outside
// the domain of the classes unless it is one the moves really reach. So the pieces of an (lr, fb) pair are a REAL arrangement:
// the first one a BFS over the L/R and F/B center permutations finds for that pair of classes (every pair of classes is reached).
static std::vector<std::array<uint8_t,8>> PAIR_LR, PAIR_FB;   // [lr * 24 + fb]

static void init_center_reps() {
    PAIR_LR.assign(576, {}); PAIR_FB.assign(576, {});
    std::vector<char> have(576, 0);
    int n_have = 0;
    std::vector<int> moves;
    for (int k = 0; k < coords::S4_NM; k++) moves.push_back(P2_TO_FULL_MOVE_INDEX[coords::S3PRIME_GOOD_MOVES_PM[k]]);
    typedef std::pair<std::array<uint8_t,8>, std::array<uint8_t,8>> Pair;
    std::vector<Pair> queue;
    std::unordered_set<uint64_t> seen;
    Pair id;
    for (int i = 0; i < 8; i++) { id.first[i] = (uint8_t)i; id.second[i] = (uint8_t)i; }
    auto key = [&](const Pair& p) { return (uint64_t)coords::rank_perm8(p.first) * 40320 + (uint64_t)coords::rank_perm8(p.second); };
    queue.push_back(id);
    seen.insert(key(id));
    for (size_t h = 0; h < queue.size(); h++) {
        const Pair cur = queue[h];
        const int fb96 = coords::FB96_RANK_OF[coords::rank_perm8(cur.second)];
        if (fb96 < 0) { printf("FATAL: an F/B arrangement reached by the S3' moves is not one of the 96\n"); exit(1); }
        const int lr = coords::C_LR.dense_of_raw[coords::CENTER2520_LR[coords::rank_perm8(cur.first)]];
        const int fb = coords::C_FB.dense_of_raw[coords::FB24_FROM_FB96RANK[fb96]];
        if (lr < 0 || fb < 0) { printf("FATAL: an arrangement reached by the S3' moves is outside the lr / fb classes\n"); exit(1); }
        if (!have[lr * 24 + fb]) { have[lr * 24 + fb] = 1; n_have++; PAIR_LR[lr * 24 + fb] = cur.first; PAIR_FB[lr * 24 + fb] = cur.second; }
        for (int m : moves) {
            Pair nx{coords::apply_move_to_lr_perm(cur.first, m), coords::apply_move_to_fb_perm(cur.second, m)};
            if (seen.insert(key(nx)).second) queue.push_back(nx);
        }
    }
    if (n_have != 576) { printf("FATAL: only %d of the 576 (lr, fb) class pairs are reached by the S3' moves\n", n_have); exit(1); }
}

static void init_raw_inverses() {
    auto inv = [](const coords::Coord& c, std::vector<int>& out) {
        out.assign(c.size, -1);
        for (int raw = 0; raw < (int)c.dense_of_raw.size(); raw++) if (c.dense_of_raw[raw] >= 0) out[c.dense_of_raw[raw]] = raw;
    };
    inv(coords::C_LAYER, RAW_LAYER); inv(coords::C_EQ, RAW_EQ); inv(coords::C_UD, RAW_UD); inv(coords::C_LR, RAW_LR); inv(coords::C_FB, RAW_FB);
}

struct Pieces { int wing[24], center[24], corner_parity; };

static void realize(int layer, int eq, int pll, int ud, int lr, int fb, Pieces& p) {
    std::array<uint8_t,12> pi;
    auto local = coords::unrank_perm8(RAW_LAYER[layer]);
    for (int i = 0; i < 8; i++) pi[coords::LAYER_IDX[i]] = (uint8_t)coords::LAYER_IDX[local[i]];
    auto tup = coords::unrank_p12_4(RAW_EQ[eq]);
    for (int j = 0; j < 4; j++) pi[coords::EQUATORIAL_IDX[j]] = (uint8_t)tup[j];
    for (int i = 0; i < 24; i++) { p.wing[i] = i; p.center[i] = i; }
    for (int i = 0; i < 12; i++) { p.wing[POS_SLOTS[i]] = POS_SLOTS[i]; p.wing[WING_ADJ[POS_SLOTS[i]]] = NEG_OF[pi[i]]; }
    auto put = [&](const int* target, const std::array<uint8_t,8>& perm) { for (int j = 0; j < 8; j++) p.center[target[perm[j]]] = target[j]; };
    put(UD_TARGET, coords::unrank_perm8(coords::UD2520_REP_RAW[RAW_UD[ud]]));
    put(LR_TARGET, PAIR_LR[lr * 24 + fb]);
    put(FB_TARGET, PAIR_FB[lr * 24 + fb]);
    p.corner_parity = pll;   // the wing parity of these pieces is even, so the PLL parity is the corner parity
}

// the dense coordinates of a set of pieces; false if they are not all in the S3'->S4 coordinate domains
static bool read_ids(const Pieces& p, coords::S4Ids& id) {
    State6 s;
    for (int i = 0; i < 24; i++) { s.wing_slot[i] = p.wing[i]; s.center_slot[i] = p.center[i]; }
    s.corner_parity = p.corner_parity;
    const int fb96 = coords::FB96_RANK_OF[compute_fb2(s)];
    if (fb96 < 0) return false;
    auto pairing = coords::compute_pairing(s.wing_slot.data());
    for (int i = 0; i < 12; i++) if (pairing[i] > 11) return false;
    for (int i = 0; i < 8; i++) if (coords::LAYER_VALUE_LOCAL[pairing[coords::LAYER_IDX[i]]] < 0) return false;
    id.layer = coords::C_LAYER.dense_of_raw[coords::layer_rank_of(pairing)];
    id.eq = coords::C_EQ.dense_of_raw[coords::equatorial_raw_of(pairing)];
    id.ud = coords::C_UD.dense_of_raw[coords::CENTER2520_UD[compute_ud2(s)]];
    id.lr = coords::C_LR.dense_of_raw[coords::CENTER2520_LR[compute_lr2(s)]];
    id.fb = coords::C_FB.dense_of_raw[coords::FB24_FROM_FB96RANK[fb96]];
    id.pll = pll_parity(s);
    return id.layer >= 0 && id.eq >= 0 && id.ud >= 0 && id.lr >= 0 && id.fb >= 0;
}

// A symmetry of the pieces: conjugation by a cube symmetry (pieces and slots relabeled alike), or the left multiplication
// by a whole-cube rotation (slots only).
static void act(const Pieces& in, Pieces& out, const int* wperm, const int* cperm, bool conj) {
    out.corner_parity = in.corner_parity;
    for (int p = 0; p < 24; p++) {
        out.wing[conj ? wperm[p] : p] = wperm[in.wing[p]];
        out.center[conj ? cperm[p] : p] = cperm[in.center[p]];
    }
}

// the images of ud and of b (layer if `layer`, else rest) under one symmetry
struct Gen { std::vector<uint16_t> ud, b; };
static Gen make_generator(const int* wperm, const int* cperm, bool conj, bool layer) {
    Gen e;
    e.ud.assign(N_UD, 0);
    e.b.assign(layer ? N_LAYER : N_REST, 0);
    auto fail = [&](const char* what, int v) { printf("FATAL: a %s of the S3'->S4 coordinates leaves the %s domain (value %d)\n", conj ? "conjugation" : "left rotation", what, v); exit(1); };
    Pieces a, b;
    coords::S4Ids id;
    for (int u = 0; u < N_UD; u++) {
        realize(0, 0, 0, u, 0, 0, a);
        act(a, b, wperm, cperm, conj);
        if (!read_ids(b, id)) fail("ud", u);
        e.ud[u] = (uint16_t)id.ud;
    }
    if (layer) {
        for (int l = 0; l < N_LAYER; l++) {
            realize(l, 0, 0, 0, 0, 0, a);
            act(a, b, wperm, cperm, conj);
            if (!read_ids(b, id)) fail("layer", l);
            e.b[l] = (uint16_t)id.layer;
        }
    } else {
        for (int r = 0; r < N_REST; r++) {
            const int fb = r % 24, lr = (r / 24) % 24, pll = (r / 576) % 2, eq = r / 1152;
            realize(0, eq, pll, 0, lr, fb, a);
            act(a, b, wperm, cperm, conj);
            if (!read_ids(b, id)) fail("rest", r);
            e.b[r] = (uint16_t)(((id.eq * 2 + id.pll) * 24 + id.lr) * 24 + id.fb);
        }
    }
    return e;
}

static Gen compose_gens(const Gen& g, const Gen& e) {   // g after e
    Gen p;
    p.ud.resize(e.ud.size()); p.b.resize(e.b.size());
    for (size_t i = 0; i < e.ud.size(); i++) p.ud[i] = g.ud[e.ud[i]];
    for (size_t i = 0; i < e.b.size(); i++) p.b[i] = g.b[e.b[i]];
    return p;
}
static uint64_t hash_gen(const Gen& e) {
    uint64_t h = 1469598103934665603ULL;
    for (uint16_t v : e.ud) h = (h ^ v) * 1099511628211ULL;
    for (uint16_t v : e.b) h = (h ^ v) * 1099511628211ULL;
    return h;
}

// A small generating subset of a family of symmetries, found on the 24-slot permutations (cheap), because every generator costs one
// full map over the 22,680 / 24,696 coordinate values (~4 ms): the group generated by the conjugation maps (or by the left
// multiplications) of a subset equals the one of the whole family when the subset generates the permutations themselves.
static std::vector<int> pick_generators(const int (*wperm)[24], const int (*cperm)[24], int n) {
    using P = std::array<uint8_t, 48>;
    auto mk = [&](int i) { P p; for (int k = 0; k < 24; k++) { p[k] = (uint8_t)wperm[i][k]; p[24 + k] = (uint8_t)cperm[i][k]; } return p; };
    auto mul = [&](const P& a, const P& b) { P r; for (int k = 0; k < 24; k++) { r[k] = a[b[k]]; r[24 + k] = a[24 + b[24 + k]]; } return r; };
    P id; for (int k = 0; k < 24; k++) { id[k] = (uint8_t)k; id[24 + k] = (uint8_t)k; }
    std::vector<P> clo = {id};
    std::vector<int> picks;
    for (int i = 0; i < n; i++) {
        if (std::find(clo.begin(), clo.end(), mk(i)) != clo.end()) continue;
        picks.push_back(i);
        std::vector<P> gens;
        for (int j : picks) gens.push_back(mk(j));
        clo.assign(1, id);
        for (size_t q = 0; q < clo.size(); q++)
            for (const P& g : gens) { const P nx = mul(g, clo[q]); if (std::find(clo.begin(), clo.end(), nx) == clo.end()) clo.push_back(nx); }
    }
    return picks;
}

// ---------------------------------------------------------------- the group, the classes of ud
// R := the closure of the generators, the classes of ud under it, the flat b maps
static void build_group(Reduced& R, bool layer, bool with_left_rotations) {
    R.nb = layer ? N_LAYER : N_REST;
    std::vector<Gen> gens;
    for (int s : pick_generators(S4_SYM_WING, S4_SYM_CENTER, NUM_S4_SYMS)) gens.push_back(make_generator(S4_SYM_WING[s], S4_SYM_CENTER[s], true, layer));
    if (with_left_rotations)
        for (int k : pick_generators(ROTATE_WING + 6, ROTATE_CENTER + 6, 3)) gens.push_back(make_generator(ROTATE_WING[6 + k], ROTATE_CENTER[6 + k], false, layer));   // x2, y2, z2 on the left
    std::vector<Gen> el(1);
    el[0].ud.resize(N_UD); el[0].b.resize(R.nb);
    for (int i = 0; i < N_UD; i++) el[0].ud[i] = (uint16_t)i;
    for (int i = 0; i < R.nb; i++) el[0].b[i] = (uint16_t)i;
    std::unordered_multimap<uint64_t, int> seen;
    seen.emplace(hash_gen(el[0]), 0);
    for (size_t i = 0; i < el.size(); i++)
        for (const Gen& g : gens) {
            Gen p = compose_gens(g, el[i]);
            const uint64_t h = hash_gen(p);
            bool known = false;
            auto range = seen.equal_range(h);
            for (auto it = range.first; it != range.second && !known; ++it) known = el[it->second].ud == p.ud && el[it->second].b == p.b;
            if (known) continue;
            if (el.size() >= 255) { printf("FATAL: the S3'->S4 symmetry group has more than 255 elements\n"); exit(1); }
            seen.emplace(h, (int)el.size());
            el.push_back(std::move(p));
        }
    R.ud.clear(); R.b.clear();
    for (auto& e : el) { R.ud.push_back(std::move(e.ud)); R.b.push_back(std::move(e.b)); }

    R.ud_info.assign(N_UD, 0);
    std::vector<int> cls_of_rep(N_UD, -1);
    R.class_rep.clear();
    for (int u = 0; u < N_UD; u++) {
        // the representative of u's orbit is its smallest image; the element reaching it is the first one that does
        int best = N_UD, elem = 0;
        for (size_t h = 0; h < R.elems(); h++)
            if (R.ud[h][u] < best) { best = R.ud[h][u]; elem = (int)h; }
        if (cls_of_rep[best] < 0) { cls_of_rep[best] = (int)R.class_rep.size(); R.class_rep.push_back((uint16_t)best); }
        R.ud_info[u] = ((uint32_t)cls_of_rep[best] << 8) | (uint32_t)elem;
    }
    R.nclass = (int)R.class_rep.size();
    R.bmap.resize(R.elems() * R.nb);
    for (size_t h = 0; h < R.elems(); h++) std::copy(R.b[h].begin(), R.b[h].end(), R.bmap.begin() + h * R.nb);
}

// ---------------------------------------------------------------- the reduced table
static uint64_t fingerprint(const Reduced& R, const coords::Coord& B, const coords::Goals& goals) {
    uint64_t h = 1469598103934665603ULL;
    auto add = [&](uint64_t v) { h = (h ^ v) * 1099511628211ULL; };
    for (int32_t v : B.trans) add((uint32_t)v);
    for (int32_t v : coords::C_UD.trans) add((uint32_t)v);
    for (auto& g : goals) { add((uint32_t)g.first); add((uint32_t)g.second); }
    // the symmetry definitions and the classes they give (not the element numbering, which depends on the generators picked)
    for (int s = 0; s < NUM_S4_SYMS; s++) for (int k = 0; k < 24; k++) { add((uint32_t)S4_SYM_WING[s][k]); add((uint32_t)S4_SYM_CENTER[s][k]); }
    for (int r = 6; r < 9; r++) for (int k = 0; k < 24; k++) { add((uint32_t)ROTATE_WING[r][k]); add((uint32_t)ROTATE_CENTER[r][k]); }
    for (uint16_t v : R.class_rep) add(v);
    add(R.elems());
    add(R.nclass);
    add(DIST_CAP);   // the stored format (nibbles capped at DIST_CAP)
    return h;
}

// The reduced table of R: loaded from `path` if its fingerprint matches, else cut out of the full table (a BFS from the goals)
// and saved. Row c is the full table's column of the class representative.
static void make_table(Reduced& R, const char* name, const coords::Coord& B, const coords::Goals& goals, const std::string& path) {
    const size_t nb = (size_t)R.nb, total = (size_t)R.nclass * nb, packed = (total + 1) / 2;
    const uint64_t fp = fingerprint(R, B, goals);
    {
        std::ifstream f(path, std::ios::binary | std::ios::ate);
        if (f && (size_t)f.tellg() == packed + sizeof(uint64_t)) {
            f.seekg((std::streamoff)packed);
            uint64_t stored = 0;
            f.read((char*)&stored, sizeof(stored));
            if (stored == fp) {
                f.seekg(0);
                R.table.resize(packed);
                f.read((char*)R.table.data(), (std::streamsize)packed);
                if (f) { printf("  %s: loaded from cache %s (%.2f MB)\n", name, path.c_str(), packed / 1e6); fflush(stdout); return; }
            }
        }
    }
    printf("  %s: building from the full BFS (no valid cache at %s)...\n", name, path.c_str());
    fflush(stdout);
    auto t0 = std::chrono::steady_clock::now();
    std::vector<uint8_t> full;
    coords::build_pair_table_bfs(B, coords::C_UD, goals, full);   // full[b * 2520 + ud]
    R.table.assign(packed, 0);
    for (int c = 0; c < R.nclass; c++)
        for (size_t b = 0; b < nb; b++) {
            const size_t i = (size_t)c * nb + b;
            const uint8_t d = std::min<int>(full[b * N_UD + R.class_rep[c]], DIST_CAP);
            R.table[i >> 1] |= (uint8_t)(d << ((i & 1) << 2));
        }
    printf("  %s: built in %.1fs\n", name, std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count());
    std::ofstream out(path, std::ios::binary);
    if (out) { out.write((const char*)R.table.data(), (std::streamsize)packed); out.write((const char*)&fp, sizeof(fp)); }
    if (!out) fprintf(stderr, "  WARNING: failed to write cache %s\n", path.c_str());
    fflush(stdout);
}

static void build(const std::string& cache_dir) {
    auto t0 = std::chrono::steady_clock::now();
    LapTimer lt;
    init_raw_inverses();
    lt.lap("raw inverses");
    init_center_reps();
    lt.lap("center representatives (lr/fb arrangements)");
    coords::Goals g1, g2;
    for (int k = 0; k < 4; k++) { g1.push_back({0, coords::S4_GOAL_UD[k]}); g2.push_back({coords::S4_GOAL_REST[k], coords::S4_GOAL_UD[k]}); }
    build_group(R1, true, true);
    lt.lap("T1 group (32 elements, classes)");
    make_table(R1, "T1 layer x ud (reduced)", coords::C_LAYER, g1, cache_dir + "/s4_sym_layer_ud.bin");
    lt.lap("T1 table (fingerprint + cache load)");
    build_group(R2, false, false);
    lt.lap("T2 group (16 elements, classes)");
    make_table(R2, "T2 (eq,pll,lr,fb) x ud (reduced)", coords::C_REST, g2, cache_dir + "/s4_sym_eqpllLRFB_ud.bin");
    lt.lap("T2 table (fingerprint + cache load)");
    g_build_ms = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
}

// Every entry of the reduced tables against the plain full BFS (the reference): `--check-s4-sym`.
static bool check_against_full() {
    coords::Goals g1, g2;
    for (int k = 0; k < 4; k++) { g1.push_back({0, coords::S4_GOAL_UD[k]}); g2.push_back({coords::S4_GOAL_REST[k], coords::S4_GOAL_UD[k]}); }
    bool ok = true;
    for (int t = 0; t < 2; t++) {
        const Reduced& R = t == 0 ? R1 : R2;
        std::vector<uint8_t> full;
        coords::build_pair_table_bfs(t == 0 ? coords::C_LAYER : coords::C_REST, coords::C_UD, t == 0 ? g1 : g2, full);
        long long bad = 0;
        for (int b = 0; b < R.nb; b++)
            for (int u = 0; u < N_UD; u++) bad += R.dist(b, u) != std::min<int>(full[(size_t)b * N_UD + u], DIST_CAP);
        printf("  check-s4-sym: T%d reduced vs full: %lld of %zu entries differ\n", t + 1, bad, full.size());
        ok = ok && bad == 0;
    }
    return ok;
}
static size_t bytes() { return R1.bytes() + R2.bytes(); }

static void print_stats() {
    auto stat = [](const char* name, const Reduced& R) {
        long long capped = 0, sum = 0; int mx = 0;
        const size_t n = (size_t)R.nclass * R.nb;
        for (size_t i = 0; i < n; i++) { const int d = R.get(i); capped += d == DIST_CAP; sum += d; mx = std::max(mx, d); }
        printf("  %s: group of %zu elements, ud in %d classes, %zu entries (4 bits), avg=%.4f max=%d (entries at the cap %d: %lld)\n", name,
               R.elems(), R.nclass, n, (double)sum / (double)n, mx, DIST_CAP, capped);
    };
    printf("  S3'->S4 symmetry-reduced tables: built in %.0f ms, %.1f MB in all\n", g_build_ms, bytes() / 1e6);
    stat("T1 layer x ud", R1);
    stat("T2 (eq,pll,lr,fb) x ud", R2);
}

// ---------------------------------------------------------------- lookup
static inline int dist1(const Tier3State& t) { return R1.dist(t.layer, t.ud); }
static inline int dist2(const Tier3State& t) { return R2.dist(t.rest, t.ud); }
static inline int tier3_dist(const Tier3State& t) { return std::max(R1.dist(t.layer, t.ud), R2.dist(t.rest, t.ud)); }

} // namespace s4sym
