// AUTO-GENERATED by generate_tables2.py. Do not edit by hand.
#pragma once

static const int P2_NUM_MOVES = 21;
static const int P2_NUM_FAMILIES = 9;
static const int WING_SOLVED_IDX = 1075035;
static const int NUM_WING_COSETS = 2704156;
static const int NUM_FB_PERMS = 40320;

static const char* P2_MOVE_NAMES[21] = {
    "U", "U2", "U'", "D", "D2", "D'", "R", "R2", "R'", "L", "L2", "L'", "F", "F2", "F'", "B", "B2", "B'", "Uw2", "Rw2", "Fw2"
};

// which of the 9 base families each phase-2 move uses, and how many
// times to apply that family's STORED transition (see WING_FAMILY_PERM /
// CENTER8_FAMILY_PERM below -- U/D/R/L/F/B store their quarter turn,
// Uw/Rw/Fw store their OWN square directly, since power 1 and 3 of the
// wide moves are not legal in phase 2)
static const int P2_MOVE_FAMILY[21] = { 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 7, 8 };

static const int P2_MOVE_REPEATS[21] = { 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 1, 1 };

// axis group per move: 0=Y(U/Uw/D) 1=X(R/Rw/L) 2=Z(F/Fw/B)
static const int P2_MOVE_GROUP[21] = { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2 };

// rank within axis group: 0=outer-near, 1=wide, 2=outer-far
static const int P2_MOVE_RANK[21] = { 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 1, 1 };

// index of each phase-2 move within the full 27-move list (tables.h's
// MOVE_NAMES/WING_PERM/CENTER_PERM), for applying a phase-2 move to a raw
// cube state (used by chain_test.cpp)
static const int P2_TO_FULL_MOVE_INDEX[21] = { 0, 1, 2, 6, 7, 8, 9, 10, 11, 15, 16, 17, 18, 19, 20, 24, 25, 26, 4, 13, 22 };

// WING_FAMILY_PERM[fam][slot] = destination slot under family fam's
// stored representative power
static const int WING_FAMILY_PERM[9][24] = {
    {0, 1, 2, 3, 4, 5, 14, 10, 8, 9, 22, 6, 12, 13, 23, 7, 16, 17, 18, 19, 20, 21, 15, 11},
    {9, 13, 2, 3, 4, 5, 6, 7, 1, 17, 10, 11, 0, 16, 14, 15, 8, 12, 18, 19, 20, 21, 22, 23},
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 19, 21, 17, 23, 16, 22, 18, 20},
    {4, 2, 6, 0, 7, 1, 5, 3, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
    {0, 1, 2, 11, 4, 15, 6, 7, 8, 5, 10, 21, 12, 3, 14, 19, 16, 17, 18, 9, 20, 13, 22, 23},
    {0, 1, 12, 3, 8, 5, 6, 7, 18, 9, 2, 11, 20, 13, 4, 15, 16, 17, 14, 19, 10, 21, 22, 23},
    {0, 1, 2, 3, 21, 20, 23, 22, 8, 9, 15, 14, 12, 13, 11, 10, 16, 17, 18, 19, 5, 4, 7, 6},
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 14, 13, 12, 23, 22, 21, 20, 19, 18, 17, 16},
    {0, 23, 2, 21, 4, 19, 6, 17, 8, 15, 10, 13, 12, 11, 14, 9, 16, 7, 18, 5, 20, 3, 22, 1},
};

// CENTER8_FAMILY_PERM[fam][i] = destination index (0..7, within the F/B
// target list) under family fam's stored representative power
static const int CENTER8_FAMILY_PERM[9][8] = {
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 3, 2, 7, 4, 1, 6, 5},
    {4, 1, 0, 3, 6, 5, 2, 7},
    {0, 1, 7, 6, 4, 5, 3, 2},
    {0, 1, 2, 3, 7, 6, 5, 4},
    {0, 7, 2, 5, 4, 3, 6, 1},
};

// the 12 wing slots that define "positive" (the S2 target coset)
static const int WING_TARGET[12] = { 0, 3, 4, 7, 9, 10, 12, 15, 17, 18, 21, 22 };

// the 96 F/B-center permutation indices (Lehmer rank, 0..40319) that
// are reachable by S2's own generators -- i.e. "solved" for this coord
static const int FB_SOLVED_INDICES[96] = { 0, 23, 288, 311, 697, 713, 722, 741, 1032, 1055, 1393, 1409, 2210, 2229, 2354, 2373, 2811, 2819, 4420, 4431, 4516, 4527, 4733, 4737, 15962, 15981, 16158, 16174, 16519, 16528, 16680, 16703, 16854, 16870, 17263, 17272, 17480, 17491, 17576, 17587, 17885, 17889, 19642, 19645, 19786, 19789, 19803, 19811, 26124, 26132, 26282, 26301, 26578, 26581, 26846, 26850, 27056, 27067, 27244, 27255, 28200, 28223, 28374, 28390, 28783, 28792, 29695, 29704, 29761, 29777, 30106, 30109, 31166, 31170, 31376, 31387, 31564, 31575, 31884, 31892, 32042, 32061, 32338, 32341, 33294, 33310, 33360, 33383, 33826, 33829, 34681, 34697, 34855, 34864, 35143, 35152 };

