// AUTO-GENERATED by generate_tables4.py. Do not edit by hand.
// Requires tables.h and tables2.h to be included first (reuses
// tables2.h's CENTER8_FAMILY_PERM for the F/B coordinate).
#pragma once

static const int P4_NUM_MOVES = 15;

static const char* P4_MOVE_NAMES[15] = {
    "U", "U2", "U'", "D", "D2", "D'", "R", "R2", "R'", "L", "L2", "L'", "F2", "B2", "Rw2"
};

// which of the 9 base families (same 9/order/stored-powers as
// tables2.h/tables3.h) each phase-4 move uses, and how many times
// to apply that family's stored transition
static const int P4_MOVE_FAMILY[15] = { 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 5, 7 };

static const int P4_MOVE_REPEATS[15] = { 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 2, 1 };

// axis group per move: 0=Y(U/Uw/D) 1=X(R/Rw/L) 2=Z(F/Fw/B)
static const int P4_MOVE_GROUP[15] = { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 1 };

// rank within axis group: 0=outer-near, 1=wide, 2=outer-far
static const int P4_MOVE_RANK[15] = { 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 1 };

// index of each phase-4 move within the full 27-move list
static const int P4_TO_FULL_MOVE_INDEX[15] = { 0, 1, 2, 6, 7, 8, 9, 10, 11, 15, 16, 17, 19, 25, 13 };

// UD_CENTER8_FAMILY_PERM[fam][i] = destination index (0..7, within
// the U/D target list) under family fam's stored representative power.
// (F/B's equivalent is tables2.h's CENTER8_FAMILY_PERM, reused as-is.)
static const int UD_CENTER8_FAMILY_PERM[9][8] = {
    {0, 1, 6, 2, 4, 5, 7, 3},
    {1, 5, 2, 3, 0, 4, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 2, 3, 4, 5, 6, 7},
    {0, 1, 7, 6, 4, 5, 3, 2},
    {0, 1, 2, 3, 7, 6, 5, 4},
    {0, 7, 2, 5, 4, 3, 6, 1},
};

// the 16 U/D-center permutation indices (Lehmer rank,
// 0..40319) that are S4-valid (unrestricted -- all 40320 reachable --
// merely inside S3)
static const int UD_SOLVED_INDICES_S4[16] = { 0, 224, 489, 713, 8064, 8258, 8427, 8621, 20310, 20508, 20677, 20875, 28374, 28542, 28615, 28783 };

// the 4 F/B-center permutation indices that are S4-valid
// (a subset of tables3.h's 24 S3-valid FB_SOLVED_INDICES_S3)
static const int FB_SOLVED_INDICES_S4[4] = { 0, 4527, 31376, 35152 };

// Wing-pairing coordinate: SIGMA_POS[move][i]/SIGMA_NEG[move][i], the
// 12-element index permutations induced by each phase-4 move on the
// positive/negative wing-orbit slot lists (POS_SLOTS/NEG_OF below).
// new_perm[SIGMA_POS[m][i]] = SIGMA_NEG[m][perm[i]] applies a move
// directly to the 12-element pairing permutation -- see phase4.py's
// module docstring for the full derivation and validation.
static const int SIGMA_POS[15][12] = {
    {0, 1, 2, 5, 4, 11, 6, 3, 8, 9, 10, 7},
    {0, 1, 2, 11, 4, 7, 6, 5, 8, 9, 10, 3},
    {0, 1, 2, 7, 4, 3, 6, 11, 8, 9, 10, 5},
    {4, 1, 2, 3, 8, 5, 0, 7, 6, 9, 10, 11},
    {8, 1, 2, 3, 6, 5, 4, 7, 0, 9, 10, 11},
    {6, 1, 2, 3, 0, 5, 8, 7, 4, 9, 10, 11},
    {0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 11, 9},
    {0, 1, 2, 3, 4, 5, 6, 7, 11, 10, 9, 8},
    {0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 8, 10},
    {2, 0, 3, 1, 4, 5, 6, 7, 8, 9, 10, 11},
    {3, 2, 1, 0, 4, 5, 6, 7, 8, 9, 10, 11},
    {1, 3, 0, 2, 4, 5, 6, 7, 8, 9, 10, 11},
    {0, 10, 2, 3, 7, 5, 6, 4, 8, 9, 1, 11},
    {0, 1, 9, 3, 4, 6, 5, 7, 8, 2, 10, 11},
    {0, 1, 2, 3, 4, 5, 7, 6, 11, 10, 9, 8},
};

static const int SIGMA_NEG[15][12] = {
    {0, 1, 2, 5, 4, 11, 6, 3, 8, 9, 10, 7},
    {0, 1, 2, 11, 4, 7, 6, 5, 8, 9, 10, 3},
    {0, 1, 2, 7, 4, 3, 6, 11, 8, 9, 10, 5},
    {4, 1, 2, 3, 8, 5, 0, 7, 6, 9, 10, 11},
    {8, 1, 2, 3, 6, 5, 4, 7, 0, 9, 10, 11},
    {6, 1, 2, 3, 0, 5, 8, 7, 4, 9, 10, 11},
    {0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 11, 9},
    {0, 1, 2, 3, 4, 5, 6, 7, 11, 10, 9, 8},
    {0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 8, 10},
    {2, 0, 3, 1, 4, 5, 6, 7, 8, 9, 10, 11},
    {3, 2, 1, 0, 4, 5, 6, 7, 8, 9, 10, 11},
    {1, 3, 0, 2, 4, 5, 6, 7, 8, 9, 10, 11},
    {0, 10, 2, 3, 7, 5, 6, 4, 8, 9, 1, 11},
    {0, 1, 9, 3, 4, 6, 5, 7, 8, 2, 10, 11},
    {0, 1, 2, 3, 5, 4, 6, 7, 11, 10, 9, 8},
};

// POS_SLOTS/NEG_OF: the 12 positive-orbit slots (canonical order) and
// their physically-paired negative-orbit slot, plus ADJ (the full
// 24-slot twin-adjacency) -- needed only for ground-truth extraction
// from a raw cube state (chain_test-style), not for the incremental
// SIGMA_POS/SIGMA_NEG move application above.
static const int POS_SLOTS[12] = { 0, 3, 4, 7, 9, 10, 12, 15, 17, 18, 21, 22 };

static const int NEG_OF[12] = { 1, 5, 2, 6, 13, 14, 8, 11, 16, 20, 19, 23 };

static const int WING_ADJ[24] = { 1, 0, 4, 5, 2, 3, 7, 6, 12, 13, 14, 15, 8, 9, 10, 11, 17, 16, 20, 21, 18, 19, 23, 22 };

