// AUTO-GENERATED by generate_tables5.py. Do not edit by hand.
#pragma once

// CORNER_PERM[m][li] = destination LOCAL index (0..23, = pos_idx*3+axis,
// pos_idx in cube_model.CORNER_POS order) of the corner STICKER at local
// index li, under move m -- structurally identical to CENTER_PERM/
// WING_PERM (pure position relabeling, no separate orientation value to
// track): apply moves AND whole-cube-rotation conjugation to a 24-element
// corner_sticker_slot array exactly the way center_slot/wing_slot are
// updated/conjugated elsewhere in this project. See generate_tables5.py's
// module docstring for why this (rather than an 8-piece slot+orientation
// pair) was chosen -- the latter's conjugation-under-rotation transform
// was verified NOT to be a simple function of (destination, old value).
//
// To get the 8 signed corner orientations (needed for the 3^7 phase-5
// coordinate) from a corner_sticker_slot snapshot, invert it, then for
// each of the 8 positions d look at which ORIGINAL sticker occupies d's
// axis-1 (Y) slot (local index d*3+1); that sticker's ORIGINAL axis (its
// local index mod 3) minus 1, mod 3, is the raw orientation -- then
// multiply by CORNER_POS_PARITY_SIGN[d] (+1 or -1) and mod 3 again. The
// sign correction is NOT optional -- found empirically that without it,
// the total-orientation invariant (sum == 0 mod 3 over all 8 corners,
// true for every reachable state) fails for the raw value. See
// signed_ori_from_sticker_perm in generate_tables5.py.
// Verified against cube_model.py's from-scratch extraction over 2000
// random move sequences (chained composition, not just single moves),
// both for the raw permutation and for the derived orientation.

static const int CORNER_PERM[27][24] = {
    {0, 1, 2, 3, 4, 5, 20, 19, 18, 8, 7, 6, 12, 13, 14, 15, 16, 17, 23, 22, 21, 11, 10, 9}, // U
    {0, 1, 2, 3, 4, 5, 21, 22, 23, 18, 19, 20, 12, 13, 14, 15, 16, 17, 9, 10, 11, 6, 7, 8}, // U2
    {0, 1, 2, 3, 4, 5, 11, 10, 9, 23, 22, 21, 12, 13, 14, 15, 16, 17, 8, 7, 6, 20, 19, 18}, // U'
    {0, 1, 2, 3, 4, 5, 20, 19, 18, 8, 7, 6, 12, 13, 14, 15, 16, 17, 23, 22, 21, 11, 10, 9}, // Uw
    {0, 1, 2, 3, 4, 5, 21, 22, 23, 18, 19, 20, 12, 13, 14, 15, 16, 17, 9, 10, 11, 6, 7, 8}, // Uw2
    {0, 1, 2, 3, 4, 5, 11, 10, 9, 23, 22, 21, 12, 13, 14, 15, 16, 17, 8, 7, 6, 20, 19, 18}, // Uw'
    {5, 4, 3, 17, 16, 15, 6, 7, 8, 9, 10, 11, 2, 1, 0, 14, 13, 12, 18, 19, 20, 21, 22, 23}, // D
    {15, 16, 17, 12, 13, 14, 6, 7, 8, 9, 10, 11, 3, 4, 5, 0, 1, 2, 18, 19, 20, 21, 22, 23}, // D2
    {14, 13, 12, 2, 1, 0, 6, 7, 8, 9, 10, 11, 17, 16, 15, 5, 4, 3, 18, 19, 20, 21, 22, 23}, // D'
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 17, 16, 21, 23, 22, 12, 14, 13, 18, 20, 19}, // R
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 21, 22, 23, 18, 19, 20, 15, 16, 17, 12, 13, 14}, // R2
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18, 20, 19, 12, 14, 13, 21, 23, 22, 15, 17, 16}, // R'
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 17, 16, 21, 23, 22, 12, 14, 13, 18, 20, 19}, // Rw
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 21, 22, 23, 18, 19, 20, 15, 16, 17, 12, 13, 14}, // Rw2
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18, 20, 19, 12, 14, 13, 21, 23, 22, 15, 17, 16}, // Rw'
    {6, 8, 7, 0, 2, 1, 9, 11, 10, 3, 5, 4, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // L
    {9, 10, 11, 6, 7, 8, 3, 4, 5, 0, 1, 2, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // L2
    {3, 5, 4, 9, 11, 10, 0, 2, 1, 6, 8, 7, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}, // L'
    {0, 1, 2, 10, 9, 11, 6, 7, 8, 22, 21, 23, 12, 13, 14, 4, 3, 5, 18, 19, 20, 16, 15, 17}, // F
    {0, 1, 2, 21, 22, 23, 6, 7, 8, 15, 16, 17, 12, 13, 14, 9, 10, 11, 18, 19, 20, 3, 4, 5}, // F2
    {0, 1, 2, 16, 15, 17, 6, 7, 8, 4, 3, 5, 12, 13, 14, 22, 21, 23, 18, 19, 20, 10, 9, 11}, // F'
    {0, 1, 2, 10, 9, 11, 6, 7, 8, 22, 21, 23, 12, 13, 14, 4, 3, 5, 18, 19, 20, 16, 15, 17}, // Fw
    {0, 1, 2, 21, 22, 23, 6, 7, 8, 15, 16, 17, 12, 13, 14, 9, 10, 11, 18, 19, 20, 3, 4, 5}, // Fw2
    {0, 1, 2, 16, 15, 17, 6, 7, 8, 4, 3, 5, 12, 13, 14, 22, 21, 23, 18, 19, 20, 10, 9, 11}, // Fw'
    {13, 12, 14, 3, 4, 5, 1, 0, 2, 9, 10, 11, 19, 18, 20, 15, 16, 17, 7, 6, 8, 21, 22, 23}, // B
    {18, 19, 20, 3, 4, 5, 12, 13, 14, 9, 10, 11, 6, 7, 8, 15, 16, 17, 0, 1, 2, 21, 22, 23}, // B2
    {7, 6, 8, 3, 4, 5, 19, 18, 20, 9, 10, 11, 1, 0, 2, 15, 16, 17, 13, 12, 14, 21, 22, 23}, // B'
};

// CORNER_POS_PARITY_SIGN[d] = +1 if corner position d (cube_model.CORNER_POS
// order) has an EVEN number of (x,y,z) coordinates equal to 3, else -1 --
// the chirality sign correction needed to derive a properly additive Z/3
// orientation coordinate (see above).
static const int CORNER_POS_PARITY_SIGN[8] = {1, -1, -1, 1, -1, 1, 1, -1};
