// AUTO-GENERATED by gen/generate-tables.mjs — do not edit by hand.
// Cubie-level move transformations for the 18 HTM moves, extracted from
// cubing.js's cube3x3x3 KPuzzle definition.
//
// Convention (matches cubing.js): applying transformation T to a state S:
//   newPieces[idx]      = S.pieces[T.permutation[idx]]
//   newOrientation[idx] = (S.orientation[T.permutation[idx]] + T.orientationDelta[idx]) % numOrientations
//
// EDGES: 12 slots, orientation mod 2. Indices 8,9,10,11 are the equator
// (E-slice) slots -- the 4 edges never touched by a U or D move.
// CORNERS: 8 slots, orientation mod 3.

export const E_SLICE_EDGE_INDICES = [8,9,10,11];

export const MOVES = {
  "U": {
    "EDGES": {
      "permutation": [
        1,
        2,
        3,
        0,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        1,
        2,
        3,
        0,
        4,
        5,
        6,
        7
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "U2": {
    "EDGES": {
      "permutation": [
        2,
        3,
        0,
        1,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        2,
        3,
        0,
        1,
        4,
        5,
        6,
        7
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "U'": {
    "EDGES": {
      "permutation": [
        3,
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        3,
        0,
        1,
        2,
        4,
        5,
        6,
        7
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "D": {
    "EDGES": {
      "permutation": [
        0,
        1,
        2,
        3,
        7,
        4,
        5,
        6,
        8,
        9,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        1,
        2,
        3,
        5,
        6,
        7,
        4
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "D2": {
    "EDGES": {
      "permutation": [
        0,
        1,
        2,
        3,
        6,
        7,
        4,
        5,
        8,
        9,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        1,
        2,
        3,
        6,
        7,
        4,
        5
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "D'": {
    "EDGES": {
      "permutation": [
        0,
        1,
        2,
        3,
        5,
        6,
        7,
        4,
        8,
        9,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        1,
        2,
        3,
        7,
        4,
        5,
        6
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "L": {
    "EDGES": {
      "permutation": [
        0,
        1,
        2,
        11,
        4,
        5,
        6,
        9,
        8,
        3,
        10,
        7
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        1,
        6,
        2,
        4,
        3,
        5,
        7
      ],
      "orientationDelta": [
        0,
        0,
        2,
        1,
        0,
        2,
        1,
        0
      ]
    }
  },
  "L2": {
    "EDGES": {
      "permutation": [
        0,
        1,
        2,
        7,
        4,
        5,
        6,
        3,
        8,
        11,
        10,
        9
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        1,
        5,
        6,
        4,
        2,
        3,
        7
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "L'": {
    "EDGES": {
      "permutation": [
        0,
        1,
        2,
        9,
        4,
        5,
        6,
        11,
        8,
        7,
        10,
        3
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        1,
        3,
        5,
        4,
        6,
        2,
        7
      ],
      "orientationDelta": [
        0,
        0,
        2,
        1,
        0,
        2,
        1,
        0
      ]
    }
  },
  "R": {
    "EDGES": {
      "permutation": [
        0,
        8,
        2,
        3,
        4,
        10,
        6,
        7,
        5,
        9,
        1,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        4,
        0,
        2,
        3,
        7,
        5,
        6,
        1
      ],
      "orientationDelta": [
        2,
        1,
        0,
        0,
        1,
        0,
        0,
        2
      ]
    }
  },
  "R2": {
    "EDGES": {
      "permutation": [
        0,
        5,
        2,
        3,
        4,
        1,
        6,
        7,
        10,
        9,
        8,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        7,
        4,
        2,
        3,
        1,
        5,
        6,
        0
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "R'": {
    "EDGES": {
      "permutation": [
        0,
        10,
        2,
        3,
        4,
        8,
        6,
        7,
        1,
        9,
        5,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        1,
        7,
        2,
        3,
        0,
        5,
        6,
        4
      ],
      "orientationDelta": [
        2,
        1,
        0,
        0,
        1,
        0,
        0,
        2
      ]
    }
  },
  "F": {
    "EDGES": {
      "permutation": [
        9,
        1,
        2,
        3,
        8,
        5,
        6,
        7,
        0,
        4,
        10,
        11
      ],
      "orientationDelta": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        3,
        1,
        2,
        5,
        0,
        4,
        6,
        7
      ],
      "orientationDelta": [
        1,
        0,
        0,
        2,
        2,
        1,
        0,
        0
      ]
    }
  },
  "F2": {
    "EDGES": {
      "permutation": [
        4,
        1,
        2,
        3,
        0,
        5,
        6,
        7,
        9,
        8,
        10,
        11
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        5,
        1,
        2,
        4,
        3,
        0,
        6,
        7
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "F'": {
    "EDGES": {
      "permutation": [
        8,
        1,
        2,
        3,
        9,
        5,
        6,
        7,
        4,
        0,
        10,
        11
      ],
      "orientationDelta": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        4,
        1,
        2,
        0,
        5,
        3,
        6,
        7
      ],
      "orientationDelta": [
        1,
        0,
        0,
        2,
        2,
        1,
        0,
        0
      ]
    }
  },
  "B": {
    "EDGES": {
      "permutation": [
        0,
        1,
        10,
        3,
        4,
        5,
        11,
        7,
        8,
        9,
        6,
        2
      ],
      "orientationDelta": [
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        1
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        7,
        1,
        3,
        4,
        5,
        2,
        6
      ],
      "orientationDelta": [
        0,
        2,
        1,
        0,
        0,
        0,
        2,
        1
      ]
    }
  },
  "B2": {
    "EDGES": {
      "permutation": [
        0,
        1,
        6,
        3,
        4,
        5,
        2,
        7,
        8,
        9,
        11,
        10
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        6,
        7,
        3,
        4,
        5,
        1,
        2
      ],
      "orientationDelta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "B'": {
    "EDGES": {
      "permutation": [
        0,
        1,
        11,
        3,
        4,
        5,
        10,
        7,
        8,
        9,
        2,
        6
      ],
      "orientationDelta": [
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        1
      ]
    },
    "CORNERS": {
      "permutation": [
        0,
        2,
        6,
        3,
        4,
        5,
        7,
        1
      ],
      "orientationDelta": [
        0,
        2,
        1,
        0,
        0,
        0,
        2,
        1
      ]
    }
  }
};
